Repository CSID-DGU/ASCP, pull requests merged in 2023-09, with the labels that each got.

#53 🎨 refactor: state, step, action
  ReinforcementLearning/ver0.1/ver0.1.1/CrewPairingEnv.py
  ReinforcementLearning/ver0.1/ver0.1.1/PolicyGradientAgent.py
  ReinforcementLearning/ver0.1/ver0.1.1/cal.py
  ReinforcementLearning/ver0.1/ver0.1.1/getData.py
  ReinforcementLearning/ver0.1/ver0.1.1/main.py
Labels: bug, 김윤지, Reinforcement Learning, fix

#57 fix: manager error 및 오류 수정
  ManagerProgram/build.gradle
  ManagerProgram/src/main/java/org/dongguk/AbstractPersistable.java
  ManagerProgram/src/main/java/org/dongguk/CommandUtil.java
  ManagerProgram/src/main/java/org/dongguk/FlightCrewPairingXlsxFileIO.java
  ManagerProgram/src/main/java/org/dongguk/Main.java
  ManagerProgram/src/main/java/org/dongguk/domain/Aircraft.java
  ManagerProgram/src/main/java/org/dongguk/domain/Airport.java
  ManagerProgram/src/main/java/org/dongguk/domain/Flight.java
  ManagerProgram/src/main/java/org/dongguk/domain/Pairing.java
  PairingCreater/.idea/shelf/Uncommitted_changes_before_Checkout_at_2023-08-30__5_27__Changes_.xml
  PairingCreater/.idea/shelf/Uncommitted_changes_before_Checkout_at_2023-08-30_오후_5_27_[Changes]/shelved.patch
  PairingCreater/src/main/java/org/dongguk/crewpairing/persistence/FlightCrewPairingXlsxFileIO.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/util/ViewAllConstraint.java
Labels: 손형준, OptaPlanner, fix, refactor

#59 🎨 🔥 refector, fix: Factory 및 xlsx 생성 삭제
  ManagerProgram/src/main/java/org/dongguk/Main.java
  PairingCreater/.idea/misc.xml
  PairingCreater/.idea/uiDesigner.xml
  PairingCreater/src/main/java/org/dongguk/crewpairing/domain/factory/DomainFactory.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/persistence/FlightCrewPairingXlsxFileIO.java
Labels: 손형준, OptaPlanner, fix

#61 🎨 fix: moving work 오류 해결
  PairingCreater/src/main/java/org/dongguk/crewpairing/domain/Pairing.java
Labels: 손형준, OptaPlanner, fix

#63 ✨ refactor: time 설정 기능 추가
  PairingCreater/src/main/java/org/dongguk/common/app/CommonApp.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/app/PairingApp.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/domain/Pairing.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/util/ViewAllConstraint.java
Labels: 손형준, OptaPlanner, refactor

#65 🎨 refactor: 강화학습에서 사용할 데이터 객체화작업 완료
  ReinforcementLearning/Aircraft.py
  ReinforcementLearning/Airport.py
  ReinforcementLearning/CrewPairingEnv.py
  ReinforcementLearning/Factory.py
  ReinforcementLearning/Flight.py
  ReinforcementLearning/IDProvider.py
  ReinforcementLearning/Pairing.py
  ReinforcementLearning/PolicyGradientAgent.py
  ReinforcementLearning/Scorecalculator.py
  ReinforcementLearning/main.py
  ReinforcementLearning/ver0.1/ver0.1.1/CrewPairingEnv.py
  ReinforcementLearning/ver0.1/ver0.1.1/PolicyGradientAgent.py
  ReinforcementLearning/ver0.1/ver0.1.1/cal.py
  ReinforcementLearning/ver0.1/ver0.1.1/getData.py
  ReinforcementLearning/ver0.1/ver0.1.1/main.py
  ReinforcementLearning/ver0.2/Aircraft.py
  ReinforcementLearning/ver0.2/Airport.py
  ReinforcementLearning/ver0.2/CrewPairingEnv.py
  ReinforcementLearning/ver0.2/Factory.py
  ReinforcementLearning/ver0.2/Flight.py
  ReinforcementLearning/ver0.2/IDProvider.py
  ReinforcementLearning/ver0.2/Pairing.py
  ReinforcementLearning/ver0.2/PolicyGradientAgent.py
  ReinforcementLearning/ver0.2/Scorecalculator.py
  ReinforcementLearning/ver0.2/main.py
Labels: 김윤지, 장동겸, Reinforcement Learning, fix

#64 🎨 refactor: 입력 단계 수정 완료
  ManagerProgram/.idea/misc.xml
  ManagerProgram/src/main/java/org/dongguk/CommandUtil.java
  ManagerProgram/src/main/java/org/dongguk/Main.java
  ReinforcementLearning/Pairing.py
Labels: 손형준, refactor

#66 fix: hard score 튀는버그 수정
  ReinforcementLearning/CrewPairingEnv.py
Labels: bug, 김윤지, 장동겸, Reinforcement Learning, fix

#68 🐛 fix: dummyFlight로 인해 발생하는 문제 수정
  ReinforcementLearning/CrewPairingEnv.py
  ReinforcementLearning/Pairing.py
  ReinforcementLearning/Scorecalculator.py
Labels: bug, 장동겸, Reinforcement Learning, fix

#70 🎨 fix: 만족도함수 변경 / 주석 정리
  PairingCreater/.idea/sonarlint/issuestore/1/6/1612311b12e0e33284949c8e2ade7a5a0703f494
  PairingCreater/.idea/sonarlint/issuestore/6/4/64a068435c43f4221ca325425a341f8405cf6aa3
  PairingCreater/.idea/sonarlint/issuestore/7/c/7c47c0c892701936587b566305c163948c90a856
  PairingCreater/.idea/sonarlint/issuestore/8/1/81db877c238834d5c38f1f1cd4694b7d6176906c
  PairingCreater/.idea/sonarlint/issuestore/8/6/86d93a1b97f55dde744d7bbd6db02b12f5f4b227
  PairingCreater/.idea/sonarlint/issuestore/a/3/a3a1ddf542e7d0d339f45cc8d0910f8890afd697
  PairingCreater/.idea/sonarlint/issuestore/a/d/addd879d3315b37cf6ad7a527cfa9a9044499df0
  PairingCreater/.idea/sonarlint/issuestore/c/3/c3a1d0c8945c364edfe883e13244b57d8736b0e7
  PairingCreater/.idea/sonarlint/issuestore/e/a/ea9743cdce24c99fd0dee978c74b63c3074b4455
  PairingCreater/.idea/sonarlint/issuestore/f/4/f418c5e5bf691bb9b6c410ff13779ebba3a80ab3
  PairingCreater/.idea/sonarlint/issuestore/f/d/fd03b230c2436dca553de096cbb6859d17cc73f8
  PairingCreater/.idea/sonarlint/issuestore/index.pb
  PairingCreater/.idea/sonarlint/securityhotspotstore/1/6/1612311b12e0e33284949c8e2ade7a5a0703f494
  PairingCreater/.idea/sonarlint/securityhotspotstore/6/4/64a068435c43f4221ca325425a341f8405cf6aa3
  PairingCreater/.idea/sonarlint/securityhotspotstore/7/c/7c47c0c892701936587b566305c163948c90a856
  PairingCreater/.idea/sonarlint/securityhotspotstore/8/6/86d93a1b97f55dde744d7bbd6db02b12f5f4b227
  PairingCreater/.idea/sonarlint/securityhotspotstore/a/3/a3a1ddf542e7d0d339f45cc8d0910f8890afd697
  PairingCreater/.idea/sonarlint/securityhotspotstore/a/d/addd879d3315b37cf6ad7a527cfa9a9044499df0
  PairingCreater/.idea/sonarlint/securityhotspotstore/c/3/c3a1d0c8945c364edfe883e13244b57d8736b0e7
  PairingCreater/.idea/sonarlint/securityhotspotstore/f/4/f418c5e5bf691bb9b6c410ff13779ebba3a80ab3
  PairingCreater/.idea/sonarlint/securityhotspotstore/index.pb
  PairingCreater/src/main/java/org/dongguk/crewpairing/app/PairingApp.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/domain/Pairing.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/score/ParingConstraintProvider.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/util/ViewAllConstraint.java
Labels: 천기정, OptaPlanner, fix

#71 🚑 fix: score 계산 문제 해결
  PairingCreater/src/main/java/org/dongguk/crewpairing/app/PairingApp.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/domain/Flight.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/domain/Pairing.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/util/ViewAllConstraint.java
Labels: bug, 손형준, OptaPlanner, fix
