Repository CSID-DGU/ASCP, pull requests merged in 2023-08, with the labels that each got.

#28 ✨ feat: flight data generator & user manual
  .gitignore
  DataAnalyze/README.md
  DataAnalyze/datatool/FlightDataGenerator.py
Labels: documentation, enhancement, 김윤지, feature, Dataset

#29 ✨ 🔥 feat: 제약조건에 따라 Cost Method 변경
  PairingCreater/src/main/java/org/dongguk/crewpairing/domain/Airport.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/domain/Flight.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/domain/Pairing.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/domain/PairingSolution.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/persistence/FlightCrewPairingXlsxFileIO.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/score/ParingConstraintProvider.java
Labels: enhancement, 손형준, OptaPlanner, feature

#34 ✨ 주요 메서드 도큐먼트 주석 추가
  PairingCreater/src/main/java/org/dongguk/crewpairing/domain/Pairing.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/score/ParingConstraintProvider.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/util/ViewAllConstraint.java
Labels: 천기정, OptaPlanner, feature

#35 🐛 state 정의 및 step ,udate 등 RL 구조 전반 변경
  ReinforcementLearning/CrewPairingEnv.py
  ReinforcementLearning/PolicyGradientAgent.py
Labels: bug, 김윤지, Reinforcement Learning, fix

#42 🔥 fix: flight s/n 추가
  PairingCreater/.idea/gradle.xml
  PairingCreater/.idea/uiDesigner.xml
  PairingCreater/build.gradle
  PairingCreater/gradlew
  PairingCreater/src/main/java/org/dongguk/crewpairing/domain/Flight.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/persistence/FlightCrewPairingXlsxFileIO.java
Labels: 손형준, OptaPlanner, fix

#44 ✨ feat: Pairing,Flight 객체화
  ReinforcementLearning/Flight.py
  ReinforcementLearning/Pairing.py
  ReinforcementLearning/__pycache__/CrewPairingEnv.cpython-38.pyc
Labels: enhancement, 장동겸, Reinforcement Learning, feature

#41 ✨ feat: RL env 환경 세팅
  .gitignore
  DataAnalyze/.gitignore
  ReinforcementLearning/.gitignore
  ReinforcementLearning/CrewPairingEnv.py
  ReinforcementLearning/PolicyGradientAgent.py
  ReinforcementLearning/README.md
  ReinforcementLearning/requirements.txt
Labels: documentation, enhancement, 김윤지, Reinforcement Learning, feature

#49 🎨 refactor: server input 형태에 맞춰서 변경
  PairingCreater/.idea/gradle.xml
  PairingCreater/src/main/java/org/dongguk/common/app/CommonApp.java
  PairingCreater/src/main/java/org/dongguk/common/business/SolutionBusiness.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/app/PairingApp.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/domain/Pairing.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/domain/PairingSolution.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/persistence/FlightCrewPairingXlsxFileIO.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/score/ParingConstraintProvider.java
Labels: 손형준, OptaPlanner, fix, refactor

#50 ✨ feat: Cycle Manager Program
  ManagerProgram/.gitignore
  ManagerProgram/.idea/.gitignore
  ManagerProgram/.idea/gradle.xml
  ManagerProgram/.idea/misc.xml
  ManagerProgram/.idea/vcs.xml
  ManagerProgram/build.gradle
  ManagerProgram/gradle/wrapper/gradle-wrapper.jar
  ManagerProgram/gradle/wrapper/gradle-wrapper.properties
  ManagerProgram/gradlew
  ManagerProgram/gradlew.bat
  ManagerProgram/settings.gradle
  ManagerProgram/src/main/java/org/dongguk/CommandUtil.java
  ManagerProgram/src/main/java/org/dongguk/Main.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/app/PairingApp.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/persistence/FlightCrewPairingXlsxFileIO.java
  PairingCreater/src/main/java/org/dongguk/crewpairing/util/ViewAllConstraint.java
Labels: 손형준, Reinforcement Learning, OptaPlanner, feature

#51 ✨ feat: 생성패턴(팩토리) 적용, 스코어 계산하는 부분 객체화하여 분리
  ReinforcementLearning/Factory.py
  ReinforcementLearning/Flight.py
  ReinforcementLearning/IDProvider.py
  ReinforcementLearning/Scorecalculator.py
Labels: 장동겸, Reinforcement Learning, feature

#52 refactor: comments & main.py
  ReinforcementLearning/CrewPairingEnv.py
  ReinforcementLearning/PolicyGradientAgent.py
  ReinforcementLearning/__pycache__/CrewPairingEnv.cpython-38.pyc
  ReinforcementLearning/main.py
Labels: 김윤지, 이우제, Reinforcement Learning, fix, refactor
